const ORDERS = {
  MARKET: 'MARKET',
  LIMIT: 'LIMIT',
  CASH_IN: 'CASH_IN',
  CASH_OUT: 'CASH_OUT',
};

const MARKET_ORDER_TYPE = {
  BUY: 'BUY',
  SELL: 'SELL',
};

const STATUSES = {
  NEW: 'NEW',
  FILLED: 'FILLED',
};

export { ORDERS, MARKET_ORDER_TYPE, STATUSES };
